"""
Django settings for bingoCards project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config
from django.contrib.messages import constants as messages
import mimetypes

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# General Configuration
SECRET_KEY = config('SECRET_KEY')
ENVIRONMENT = config('DJANGO_ENV')

# Development settings
if ENVIRONMENT == 'development':
    DEBUG = True
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    CSRF_COOKIE_SECURE = False

# Production settings
elif ENVIRONMENT == 'production':
    DEBUG = False
    ALLOWED_HOSTS = ['gotitbingo.com']
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_DOMAIN = '.gotitbingo.com'
    CSRF_TRUSTED_ORIGINS = ['https://gotitbingo.com']

# Sandbox settings
elif ENVIRONMENT == 'sandbox':
    DEBUG = False
    ALLOWED_HOSTS = ['gotitbingo-sandbox.hyperionhub.dev']
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_DOMAIN = '.hyperionhub.dev'
    CSRF_TRUSTED_ORIGINS = ['https://gotitbingo-sandbox.hyperionhub.dev']

# Test server settings
elif ENVIRONMENT == 'test':
    DEBUG = True
    ALLOWED_HOSTS = ['gotitbingo.hyperionhub.dev']
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_DOMAIN = 'gotitbingo.hyperionhub.dev'
    CSRF_TRUSTED_ORIGINS = ['https://gotitbingo.hyperionhub.dev']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes'
    'widget_tweaks',
    'anymail',
    'bingo',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.CheckPasswordResetMiddleware',
    'axes.middleware.AxesMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'bingoCards.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bingoCards.wsgi.application'


# Database Configuration
if ENVIRONMENT == 'production':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('PROD_DATABASE_NAME'),
            'USER': config('PROD_DATABASE_USER'),
            'PASSWORD': config('PROD_DATABASE_PASSWORD'),
            'HOST': config('PROD_DATABASE_HOST'),
            'PORT': config('PROD_DATABASE_PORT'),
        }
    }
elif ENVIRONMENT == 'test':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('TEST_DATABASE_NAME', default='test_db'),
            'USER': config('TEST_DATABASE_USER', default='test_user'),
            'PASSWORD': config('TEST_DATABASE_PASSWORD', default='test_password'),
            'HOST': config('TEST_DATABASE_HOST', default='localhost'),
            'PORT': config('TEST_DATABASE_PORT', default='5432'),
        }
    }
elif ENVIRONMENT == 'sandbox':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('SBX_DATABASE_NAME', default='test_db'),
            'USER': config('SBX_DATABASE_USER', default='test_user'),
            'PASSWORD': config('SBX_DATABASE_PASSWORD', default='test_password'),
            'HOST': config('SBX_DATABASE_HOST', default='localhost'),
            'PORT': config('SBX_DATABASE_PORT', default='5432'),
        }
    }
elif ENVIRONMENT == 'development':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DEV_DATABASE_NAME', default='test_db'),
            'USER': config('DEV_DATABASE_USER', default='test_user'),
            'PASSWORD': config('DEV_DATABASE_PASSWORD', default='test_password'),
            'HOST': config('DEV_DATABASE_HOST', default='localhost'),
            'PORT': config('DEV_DATABASE_PORT', default='5433'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Django Axes Configuration
AXES_FAILURE_LIMIT = 5
AXES_LOCK_OUT_AT_FAILURE = True
AXES_COOLOFF_TIME = 1  # hours
AXES_USE_USER_AGENT = True
AXES_LOCKOUT_TEMPLATE = 'users/lockout.html'

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Chicago'
USE_TZ = True
USE_L10N = True

# Static files
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'
STATICFILES_DIRS = [str(BASE_DIR / 'static')]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
AUTH_USER_MODEL = 'users.AppUser'

# Login URL
LOGIN_URL = 'users:login'

# Login Redirection
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Email Configuration
EMAIL_BACKEND = "anymail.backends.mailjet.EmailBackend"
ANYMAIL = {
    "MAILJET_API_KEY": config('MAILJET_API_KEY'),
    "MAILJET_SECRET_KEY": config('MAILJET_API_SECRET'),
}

DEFAULT_FROM_EMAIL = config('MAILJET_FROM_EMAIL')
SERVER_EMAIL = config('MAILJET_FROM_EMAIL')
