"""
Django settings for bingoCards project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
from decouple import config
from django.contrib.messages import constants as messages
import mimetypes

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# General Configuration
SECRET_KEY = config('SECRET_KEY')
ENVIRONMENT = config('DJANGO_ENV')
PASSWORD_RESET_TIMEOUT = 3600  # 1 hour


# Debug and Allowed Hosts
if ENVIRONMENT == 'development':
    DEBUG = True
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
elif ENVIRONMENT == 'test':
    DEBUG = True
    ALLOWED_HOSTS = ['icsmanager.ncffapps.dev']
elif ENVIRONMENT == 'production':
    DEBUG = False
    ALLOWED_HOSTS = ['icsmanager.communityportals.org']


# Security Configuration
CSRF_COOKIE_SECURE = ENVIRONMENT != 'development'
CSRF_USE_SESSIONS = True

if ENVIRONMENT in ['test', 'production']:
    SECURE_SSL_REDIRECT = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

    if ENVIRONMENT == 'production':
        CSRF_COOKIE_DOMAIN = '.gotitbingo.com'
        CSRF_TRUSTED_ORIGINS = [
            'https://gotitbingo.com',
            'https://*.gotitbingo.com'
        ]
        SECURE_HSTS_SECONDS = 31536000
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True
    elif ENVIRONMENT == 'test':
        CSRF_COOKIE_DOMAIN = 'gotitbingo.hyperionhub.dev'
        CSRF_TRUSTED_ORIGINS = ['https://hyperionhub.dev']
        SECURE_HSTS_SECONDS = 3600  # 1 hour


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',
    'widget_tweaks',
    'anymail',
    'bingo',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.CheckPasswordResetMiddleware',
    'axes.middleware.AxesMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'bingoCards.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bingoCards.wsgi.application'


# Database Configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config(f'{ENVIRONMENT.upper()}_DATABASE_NAME', default='db_name'),
        'USER': config(f'{ENVIRONMENT.upper()}_DATABASE_USER', default='db_user'),
        'PASSWORD': config(f'{ENVIRONMENT.upper()}_DATABASE_PASSWORD', default='db_password'),
        'HOST': config(f'{ENVIRONMENT.upper()}_DATABASE_HOST', default='localhost'),
        'PORT': config(f'{ENVIRONMENT.upper()}_DATABASE_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Django Axes Configuration
AXES_FAILURE_LIMIT = 5
AXES_LOCK_OUT_AT_FAILURE = True
AXES_COOLOFF_TIME = lambda request: timedelta(hours=2)
AXES_LOCKOUT_TEMPLATE = 'users/lockout.html'

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Chicago'
USE_TZ = True
USE_L10N = True

# Static files
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'
STATICFILES_DIRS = [str(BASE_DIR / 'static')]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
AUTH_USER_MODEL = 'users.AppUser'

# Login URL
LOGIN_URL = 'users:login'

# Login Redirection
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Email Configuration
EMAIL_BACKEND = "anymail.backends.mailjet.EmailBackend"
ANYMAIL = {
    "MAILJET_API_KEY": config('MAILJET_API_KEY'),
    "MAILJET_SECRET_KEY": config('MAILJET_API_SECRET'),
}

DEFAULT_FROM_EMAIL = config('MAILJET_FROM_EMAIL')
SERVER_EMAIL = config('MAILJET_FROM_EMAIL')
